export const ADD_TO_FAV_LIST = "ADD_TO_FAV_LIST";
export const ADD_TO_FAV_LIST_ERROR = "ADD_TO_FAV_LIST_ERROR";

export const REMOVE_FROM_FAV_LIST = "REMOVE_FROM_FAV_LIST";
export const REMOVE_FROM_FAV_LIST_ERROR = "REMOVE_FROM_FAV_LIST_ERROR";

export const FETCH_FAV_MOVIES = "FETCH_FAV_MOVIES";
export const FETCH_FAV_MOVIES_ERROR = "FETCH_FAV_MOVIES_ERROR";
